from __future__ import annotations

import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from adapters.database.config import DatabaseSettings
from adapters.database.metadata import metadata
from adapters.database.safety import (
    ConnectionPolicy,
    verify_connected_unix_socket_target,
)
from adapters.database import tables  # noqa: F401 - registers tables on metadata

config = context.config
if config.config_file_name:
    fileConfig(config.config_file_name)

target_metadata = metadata

#: Prepended to an offline (`--sql`) script, as SQL comments so the script stays
#: valid. Offline mode never opens a connection, so the live check below cannot
#: run and the operator carries that obligation instead. See
#: `docs/operations/database-development.md`, "Offline (--sql) migrations".
OFFLINE_WARNING = """\
-- ---------------------------------------------------------------------------
-- Generated by Alembic in offline (--sql) mode.
--
-- Alembic did not connect to any server to produce this script. DATABASE_URL
-- was validated statically -- correct environment, correct database name, a
-- single target, and a PostgreSQL Unix-domain socket rather than TCP -- but a
-- URL is not a connection, so NOTHING HERE PROVES WHICH SERVER OR DATABASE
-- THIS SCRIPT WILL BE APPLIED TO.
--
-- The live check that online migrations run (current_database(), plus proof
-- that the connection is a Unix-domain socket, on the connection the DDL uses)
-- has no equivalent here. Before applying this script, confirm the target on
-- the connection that will apply it:
--
--     SELECT current_database(), inet_server_addr(), inet_client_addr();
--
-- Both addresses must be NULL: that is a Unix-domain socket, which is a file on
-- the local host. Loopback addresses are NOT sufficient -- an SSH local port
-- forward to a remote server answers with loopback at both ends exactly as a
-- local server does.
--
-- Take a backup first. Prefer `alembic upgrade head` online, which verifies the
-- connection itself and refuses a target it cannot prove.
-- ---------------------------------------------------------------------------
"""


def database_settings() -> DatabaseSettings:
    """Resolve and validate the migration target before anything connects.

    Migrations create and drop tables, so the target is validated first.
    ``APP_ENVIRONMENT`` defaults to ``development`` so an unqualified
    ``alembic upgrade`` can only ever reach the development database, never
    staging or production.

    This is the *static* half of the boundary. It refuses a multi-host or
    otherwise multi-valued target, because such a URL names more than one server
    and no single one of them can be validated; and it refuses a TCP URL,
    including a loopback one, because a schema change must run over the local
    Unix-domain socket. `127.0.0.1:5432` can be an SSH local port forward to a
    PostgreSQL server on another machine, and neither the URL nor the addresses
    that server reports can tell the difference.
    """
    value = os.environ.get("DATABASE_URL")
    if not value:
        raise RuntimeError("DATABASE_URL is required to run database migrations.")
    environment = os.environ.get("APP_ENVIRONMENT", "development")
    return DatabaseSettings.from_mapping(
        {"DATABASE_URL": value},
        environment=environment,
        policy=ConnectionPolicy.UNIX_SOCKET_ONLY,
    )


def run_migrations_offline() -> None:
    """Emit SQL without connecting.

    The static validation still applies, so an unverifiable URL is refused here
    exactly as it is online. What cannot happen offline is the live check: there
    is no connection to interrogate. That limitation is written into the script
    itself rather than left implicit.
    """
    settings = database_settings()
    print(OFFLINE_WARNING, file=sys.stdout)
    context.configure(
        url=settings.url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    settings = database_settings()
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = settings.url
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        # The URL was validated before connecting, but a URL is not a
        # connection. A `localhost` remapped in /etc/hosts, an inherited PGHOST
        # or a failover target can land somewhere the URL never named, so the
        # server is asked where this connection actually is — on the same
        # connection the migrations will use — before any DDL runs. The answer
        # must be the expected database over a Unix-domain socket; loopback
        # addresses are not accepted, because a forwarded port produces exactly
        # the same answer as a local TCP connection.
        verify_connected_unix_socket_target(
            connection, expected_database=settings.identity.database
        )
        # That query implicitly began a transaction. Alembic's own
        # `begin_transaction()` would then nest inside it and commit only the
        # inner marker, so the migration's DDL would be rolled back when the
        # connection closed — a migration that reports success and changes
        # nothing. Ending the read here leaves Alembic to own the transaction.
        connection.rollback()
        context.configure(connection=connection, target_metadata=target_metadata, compare_type=True)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
