"""Provision the disposable rp11-launch build root from the pinned archive.

Class **P** tooling (proposal §5.3.6, X-1 and X-2). It runs on the host,
outside the build root, and is **not** pinned by `toolchain.lock`: its product,
the root, is bound file by file by `build-root.manifest` (R-1), and its residual
influence is HA-3. It never installs anything on the host and needs no
privilege.

Two commands:

``resolve``
    Read the signed archive index at the pinned snapshot, compute the
    dependency closure of the seed packages, and print the package lines for
    `toolchain.lock`. Used once, when the pin is chosen or changed.

``install``
    Read the package lines from `toolchain.lock`, download each package file
    from the snapshot, **verify its SHA-256 against the lock before using it**,
    unpack it into an empty directory, and apply the fixed provisioning steps
    below. Maintainer scripts are not run.

What the archive signature proves: `InRelease` is checked with the host's
`gpgv` against the host's Ubuntu archive keyring (both class P); the index's
SHA-256 is checked against `InRelease`; and every package's SHA-256 is checked
against the index and against the lock. After provisioning, nothing about the
download matters: R-1 compares the root with the committed manifest.

Fixed provisioning steps (applied instead of maintainer scripts):

1. ``/etc/passwd`` and ``/etc/group`` from base-passwd's master files, plus the
   two unprivileged build users of R-2 and R-4(c) (``rp11build`` 1000:1000,
   ``rp11alt`` 1001:1001).
2. ``/tmp`` and ``/var/tmp`` exist, are empty, and have mode 1777.
3. The mount points ``/rp11/co``, ``/rp11/alt/checkout`` and ``/rp11/trace``
   exist as empty directories (the checkout and the IC-1 trace are bound
   there; §5.3.2 excludes the checkout from the manifest).
4. ``/etc/ld.so.cache`` is generated by the root's own ``ldconfig``, run inside
   the root by the entry mechanism (X-2).
"""
from __future__ import annotations

import argparse
import hashlib
import io
import lzma
import os
import shutil
import stat
import subprocess
import sys
import tarfile
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
LOCK = HERE.parent / "toolchain.lock"
KEYRING = Path("/usr/share/keyrings/ubuntu-archive-keyring.gpg")
SNAPSHOT_BASE = "https://snapshot.ubuntu.com/ubuntu"

#: The seed set: a minimal base system and the toolchain (§5.3.2). Everything
#: else in the root is their Pre-Depends/Depends closure.
SEEDS = (
    "base-files", "base-passwd", "dash", "coreutils-from-gnu", "findutils",
    "libc-bin", "gcc-15", "binutils", "libc6-dev", "strace",
)
#: Where an alternative or virtual dependency has several candidates, these
#: are chosen, so that the closure does not depend on index order.
PREFERRED = ("coreutils-from-gnu", "gnu-coreutils", "mawk", "libc6-dev")

BUILD_USERS = (("rp11build", 1000), ("rp11alt", 1001))
MOUNT_POINTS = ("rp11/co", "rp11/alt/checkout", "rp11/trace")


# ---------------------------------------------------------------------------
# archive index
# ---------------------------------------------------------------------------


def _fetch(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=120) as resp:  # noqa: S310 - pinned https URL
        return resp.read()


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_index(snapshot: str, suite: str, cache: Path) -> dict[str, dict[str, str]]:
    base = f"{SNAPSHOT_BASE}/{snapshot}/dists/{suite}"
    cache.mkdir(parents=True, exist_ok=True)
    inrelease = cache / "InRelease"
    inrelease.write_bytes(_fetch(f"{base}/InRelease"))
    subprocess.run(["gpgv", "--keyring", str(KEYRING), str(inrelease)], check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    want = None
    in_sha = False
    for line in inrelease.read_text().splitlines():
        if line.startswith("SHA256:"):
            in_sha = True
            continue
        if in_sha and not line.startswith(" "):
            in_sha = False
        if in_sha and line.split()[-1] == "main/binary-amd64/Packages.xz":
            want = line.split()[0]
    if want is None:
        raise SystemExit("InRelease names no main/binary-amd64/Packages.xz")
    packed = _fetch(f"{base}/main/binary-amd64/Packages.xz")
    if _sha256(packed) != want:
        raise SystemExit("Packages.xz digest differs from the signed InRelease")
    text = lzma.decompress(packed).decode("utf-8")
    index: dict[str, dict[str, str]] = {}
    for stanza in text.split("\n\n"):
        fields: dict[str, str] = {}
        key = None
        for line in stanza.splitlines():
            if line.startswith(" ") and key:
                fields[key] += "\n" + line
                continue
            key, _, value = line.partition(":")
            fields[key] = value.strip()
        if "Package" in fields:
            index[fields["Package"]] = fields
    return index


# ---------------------------------------------------------------------------
# dpkg version comparison (Debian Policy §5.6.12), used only to check that
# every versioned dependency is satisfied by the one version the index offers
# ---------------------------------------------------------------------------


def _order(c: str) -> int:
    if c == "~":
        return -1
    if c.isdigit():
        return 0
    if c.isalpha():
        return ord(c)
    return ord(c) + 256


def _cmp_part(a: str, b: str) -> int:
    while a or b:
        while (a and not a[0].isdigit()) or (b and not b[0].isdigit()):
            ca = _order(a[0]) if a and not a[0].isdigit() else 0
            cb = _order(b[0]) if b and not b[0].isdigit() else 0
            if ca != cb:
                return ca - cb
            a = a[1:] if a and not a[0].isdigit() else a
            b = b[1:] if b and not b[0].isdigit() else b
        da = len(a) - len(a.lstrip("0123456789"))
        db = len(b) - len(b.lstrip("0123456789"))
        na, nb = int(a[:da] or 0), int(b[:db] or 0)
        if na != nb:
            return na - nb
        a, b = a[da:], b[db:]
    return 0


def _split(v: str) -> tuple[int, str, str]:
    epoch = 0
    if ":" in v:
        e, v = v.split(":", 1)
        epoch = int(e)
    up, _, rev = v.rpartition("-") if "-" in v else (v, "", "0")
    return epoch, up, rev


def version_cmp(a: str, b: str) -> int:
    ea, ua, ra = _split(a)
    eb, ub, rb = _split(b)
    if ea != eb:
        return ea - eb
    return _cmp_part(ua, ub) or _cmp_part(ra, rb)


def _satisfies(version: str, op: str, want: str) -> bool:
    c = version_cmp(version, want)
    return {"=": c == 0, ">=": c >= 0, "<=": c <= 0, ">>": c > 0, "<<": c < 0}[op]


# ---------------------------------------------------------------------------
# closure
# ---------------------------------------------------------------------------


def _parse_deps(field: str) -> list[list[tuple[str, str | None, str | None]]]:
    groups = []
    for group in field.split(","):
        group = group.strip()
        if not group:
            continue
        alts = []
        for alt in group.split("|"):
            alt = alt.strip()
            name = alt.split()[0].split(":")[0]
            op = want = None
            if "(" in alt:
                inner = alt[alt.index("(") + 1:alt.index(")")].split()
                op, want = inner[0], inner[1]
            alts.append((name, op, want))
        groups.append(alts)
    return groups


def resolve(index: dict[str, dict[str, str]]) -> list[str]:
    providers: dict[str, list[str]] = {}
    for name, f in index.items():
        for p in _parse_deps(f.get("Provides", "")):
            providers.setdefault(p[0][0], []).append(name)
    chosen: list[str] = []
    todo = list(SEEDS)

    def pick(alts) -> str:
        for name, op, want in alts:
            if name in chosen or name in todo:
                return name
            for prov in providers.get(name, ()):
                if prov in chosen or prov in todo:
                    return prov
        for pref in PREFERRED:
            for name, _op, _want in alts:
                if pref == name or pref in providers.get(name, ()):
                    return pref
        for name, op, want in alts:
            if name in index:
                if op and not _satisfies(index[name]["Version"], op, want):
                    continue
                return name
            cands = sorted(providers.get(name, ()))
            if cands:
                return cands[0]
        raise SystemExit(f"unsatisfiable dependency {alts}")

    while todo:
        name = todo.pop(0)
        if name in chosen:
            continue
        if name not in index:
            raise SystemExit(f"{name} is not in the index")
        chosen.append(name)
        f = index[name]
        for field in ("Pre-Depends", "Depends"):
            for alts in _parse_deps(f.get(field, "")):
                dep = pick(alts)
                for n, op, want in alts:
                    if n == dep and op and not _satisfies(index[dep]["Version"], op, want):
                        raise SystemExit(f"{name}: {dep} {index[dep]['Version']} fails {op} {want}")
                if dep not in chosen and dep not in todo:
                    todo.append(dep)
    lines = []
    for name in sorted(chosen):
        f = index[name]
        lines.append(f"package={name} {f['Version']} {f['SHA256']} {f['Filename']}")
    return lines


# ---------------------------------------------------------------------------
# install
# ---------------------------------------------------------------------------


def read_lock(path: Path) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for line in path.read_text().splitlines():
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out.setdefault(k, []).append(v)
    return out


def _ar_members(data: bytes) -> dict[str, bytes]:
    if data[:8] != b"!<arch>\n":
        raise SystemExit("not an ar archive")
    pos, out = 8, {}
    while pos < len(data):
        hdr = data[pos:pos + 60]
        name = hdr[:16].decode().strip().rstrip("/")
        size = int(hdr[48:58].decode().strip())
        out[name] = data[pos + 60:pos + 60 + size]
        pos += 60 + size + (size & 1)
    return out


def _data_tar(deb: bytes) -> bytes:
    members = _ar_members(deb)
    for name, blob in members.items():
        if name.startswith("data.tar"):
            if name.endswith(".xz"):
                return lzma.decompress(blob)
            if name.endswith(".zst"):
                return subprocess.run(["zstd", "-dc"], input=blob, check=True,
                                      stdout=subprocess.PIPE).stdout
            if name.endswith(".tar"):
                return blob
            raise SystemExit(f"unsupported member {name}")
    raise SystemExit("no data.tar member")


def _unpack(tar_bytes: bytes, root: Path) -> None:
    with tarfile.open(fileobj=io.BytesIO(tar_bytes), mode="r:") as tf:
        for m in tf.getmembers():
            rel = os.path.normpath(m.name)
            if rel in (".", "") or rel.startswith(".."):
                continue
            dest = root / rel
            if m.isdir():
                dest.mkdir(parents=True, exist_ok=True)
                os.chmod(dest, m.mode & 0o7777)
            elif m.issym():
                dest.parent.mkdir(parents=True, exist_ok=True)
                if dest.is_symlink() or dest.exists():
                    dest.unlink()
                os.symlink(m.linkname, dest)
            elif m.islnk():
                src = root / os.path.normpath(m.linkname)
                if dest.exists() or dest.is_symlink():
                    dest.unlink()
                os.link(src, dest)
            elif m.isfile():
                dest.parent.mkdir(parents=True, exist_ok=True)
                if dest.is_symlink() or dest.exists():
                    dest.unlink()
                with tf.extractfile(m) as src, open(dest, "wb") as out:
                    shutil.copyfileobj(src, out)
                os.chmod(dest, m.mode & 0o7777)
            else:
                raise SystemExit(f"unsupported tar member type in {m.name}")


def install(lock: Path, root: Path, cache: Path) -> None:
    fields = read_lock(lock)
    snapshot = fields["archive_snapshot"][0]
    if root.exists() and any(root.iterdir()):
        raise SystemExit(f"{root} is not empty")
    root.mkdir(parents=True, exist_ok=True)
    cache.mkdir(parents=True, exist_ok=True)
    # Unpack in name order, so that a file shipped by two packages resolves
    # the same way every time.
    for line in sorted(fields["package"]):
        name, version, sha, filename = line.split()
        deb_path = cache / Path(filename).name
        if not deb_path.exists() or _sha256(deb_path.read_bytes()) != sha:
            deb_path.write_bytes(_fetch(f"{SNAPSHOT_BASE}/{snapshot}/{filename}"))
        data = deb_path.read_bytes()
        if _sha256(data) != sha:
            raise SystemExit(f"{name} {version}: package SHA-256 differs from the lock")
        _unpack(_data_tar(data), root)
    _post_install(root)


def _post_install(root: Path) -> None:
    etc = root / "etc"
    passwd = (root / "usr/share/base-passwd/passwd.master").read_text()
    group = (root / "usr/share/base-passwd/group.master").read_text()
    for name, uid in BUILD_USERS:
        passwd += f"{name}:x:{uid}:{uid}:rp11-launch build user:/nonexistent:/usr/sbin/nologin\n"
        group += f"{name}:x:{uid}:\n"
    for path, text in ((etc / "passwd", passwd), (etc / "group", group)):
        path.write_text(text)
        os.chmod(path, 0o644)
    for d in ("tmp", "var/tmp"):
        p = root / d
        p.mkdir(parents=True, exist_ok=True)
        if any(p.iterdir()):
            raise SystemExit(f"/{d} is not empty after unpacking")
        os.chmod(p, 0o1777)
    for mp in MOUNT_POINTS:
        (root / mp).mkdir(parents=True, exist_ok=True)
    for d in ("rp11", "rp11/alt", *MOUNT_POINTS):
        os.chmod(root / d, 0o755)
    os.chmod(root, 0o755)
    if (root / "etc/ld.so.preload").exists():
        raise SystemExit("/etc/ld.so.preload must be absent")


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    sub = p.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("resolve")
    r.add_argument("--snapshot", required=True)
    r.add_argument("--suite", default="resolute")
    r.add_argument("--cache", type=Path, required=True)
    i = sub.add_parser("install")
    i.add_argument("--lock", type=Path, default=LOCK)
    i.add_argument("--root", type=Path, required=True)
    i.add_argument("--cache", type=Path, required=True)
    args = p.parse_args(argv)
    if args.cmd == "resolve":
        for line in resolve(load_index(args.snapshot, args.suite, args.cache)):
            print(line)
    else:
        install(args.lock, args.root, args.cache)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
